// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OnlineFoodOrdering.Api.Data;

#nullable disable

namespace OnlineFoodOrdering.Api.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260730110531_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.20");

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.HasKey("MenuItemId");

                    b.ToTable("MenuItems");

                    b.HasData(
                        new
                        {
                            MenuItemId = 1,
                            Category = "Pizza",
                            IsAvailable = true,
                            Name = "Margherita Pizza",
                            Price = 9.99m
                        },
                        new
                        {
                            MenuItemId = 2,
                            Category = "Burger",
                            IsAvailable = true,
                            Name = "Veg Burger",
                            Price = 7.49m
                        },
                        new
                        {
                            MenuItemId = 3,
                            Category = "Beverage",
                            IsAvailable = true,
                            Name = "Coke",
                            Price = 1.99m
                        },
                        new
                        {
                            MenuItemId = 4,
                            Category = "Sides",
                            IsAvailable = true,
                            Name = "French Fries",
                            Price = 3.49m
                        },
                        new
                        {
                            MenuItemId = 5,
                            Category = "Rice",
                            IsAvailable = true,
                            Name = "Chicken Biryani",
                            Price = 11.99m
                        });
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("OrderId");

                    b.HasIndex("CustomerId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            PasswordHash = "pass123",
                            Role = "Staff",
                            Username = "staff1"
                        },
                        new
                        {
                            UserId = 2,
                            PasswordHash = "pass123",
                            Role = "Customer",
                            Username = "customer1"
                        },
                        new
                        {
                            UserId = 3,
                            PasswordHash = "pass123",
                            Role = "DeliveryAgent",
                            Username = "delivery1"
                        });
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.Order", b =>
                {
                    b.HasOne("OnlineFoodOrdering.Api.Models.User", null)
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.OrderItem", b =>
                {
                    b.HasOne("OnlineFoodOrdering.Api.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("OnlineFoodOrdering.Api.Models.Order", null)
                        .WithMany("Items")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OnlineFoodOrdering.Api.Models.Order", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
